### ISSUE TITLE
Can't find dxc stuff when building

### ISSUE THREAD

**Issue by Likailei** [JX-Master/LunaSDK#67]
用VS构建项目时提示缺少dxc的相关文件，请问应该怎么把它加入进来，需要单独克隆下来编译完加进来还是已有现成脚本？
not familiar with xmake, so what shoud I do to integrating the dxc Module to this project? get error that can't find dxc stuff when building in visual studio

**Comment by JX-Master** [comment]
Try execute `setup.bat` or `setup.sh` on root directory before building.

**Comment by Likailei** [comment]
It worked. Thanks. But it's still strange, I've already follow the steps to run this script from the beginning
